import type { Severity } from './contracts.js';

export interface Rule {
  id: string;
  severity: Severity;
  expression: RegExp;
  reason: string;
  suggestion: string;
  scope?: 'sentence' | 'line';
}

/** Reviewed static sentence-compatible rules shipped in @holdyourvoice/hyv@2.9.24. */
export const rules: Rule[] = [
  { id: "ai.delve", severity: "red", expression: /\bdelve\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use a specific verb: dig, explore, look at" },
  { id: "ai.leverage", severity: "red", expression: /\bleverage\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: use, apply, build on" },
  { id: "ai.tapestry", severity: "red", expression: /\btapestry\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "be specific about what you mean" },
  { id: "ai.holistic", severity: "red", expression: /\bholistic\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe the actual approach" },
  { id: "ai.robust", severity: "yellow", expression: /\brobust\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "say what actually makes it strong" },
  { id: "ai.pivotal", severity: "yellow", expression: /\bpivotal\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "say why it matters specifically" },
  { id: "ai.foster", severity: "yellow", expression: /\bfoster\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: build, grow, encourage, support" },
  { id: "ai.harness", severity: "yellow", expression: /\bharness\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: use, apply, work with" },
  { id: "ai.illuminate", severity: "yellow", expression: /\billuminate\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: show, explain, highlight" },
  { id: "ai.ever-evolving", severity: "red", expression: /\b(?:ever[\s-]evolving|ever[\s-]changing)\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "cut this \u2014 it says nothing" },
  { id: "ai.fast-paced", severity: "red", expression: /\bfast[\s-]paced\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "cut this \u2014 every industry says this" },
  { id: "ai.game-changer", severity: "red", expression: /\bgame[\s-]changer\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "explain what actually changed" },
  { id: "ai.paradigm", severity: "red", expression: /\bparadigm\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe the actual shift" },
  { id: "ai.synergy", severity: "red", expression: /\bsynergy\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what works together and why" },
  { id: "ai.ecosystem", severity: "yellow", expression: /\becosystem\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific tools/partners/platforms" },
  { id: "ai.seamless", severity: "yellow", expression: /\bseamless\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe how it actually works" },
  { id: "ai.actionable", severity: "yellow", expression: /\bactionable\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just give the action, don't label it" },
  { id: "ai.granular", severity: "yellow", expression: /\bgranular\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "say: specific, detailed, or name the level" },
  { id: "ai.impactful", severity: "yellow", expression: /\bimpactful\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe the actual impact" },
  { id: "ai.transform", severity: "yellow", expression: /\btransform\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what specifically changed" },
  { id: "ai.empower", severity: "yellow", expression: /\bempower\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what people can actually do" },
  { id: "ai.unlock", severity: "yellow", expression: /\bunlock\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what they get access to" },
  { id: "ai.nuanced", severity: "yellow", expression: /\bnuanced\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "explain the specific complexity" },
  { id: "ai.multifaceted", severity: "red", expression: /\bmultifaceted\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific aspects" },
  { id: "ai.comprehensive", severity: "yellow", expression: /\bcomprehensive\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "say what it covers specifically" },
  { id: "ai.innovative", severity: "yellow", expression: /\binnovative\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what's actually new" },
  { id: "ai.cut[t]?ing-edge", severity: "red", expression: /\bcut(?:t)?ing[\s-]edge\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific technology" },
  { id: "ai.state-of-the-art", severity: "red", expression: /\bstate[\s-]of[\s-]the[\s-]art\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what makes it current" },
  { id: "ai.best-practices", severity: "yellow", expression: /\bbest[\s-]practices?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific practice" },
  { id: "ai.world-class", severity: "red", expression: /\bworld[\s-]class\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "prove it with specifics" },
  { id: "ai.second-to-none", severity: "red", expression: /\bsecond[\s-]to[\s-]none\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "drop the superlative, show the work" },
  { id: "ai.utilize", severity: "red", expression: /\butilize[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'use "use" instead' },
  { id: "ai.landscape", severity: "red", expression: /\blandscape\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific market/field/area" },
  { id: "ai.realm", severity: "red", expression: /\brealm\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific domain" },
  { id: "ai.straightforward", severity: "yellow", expression: /\bstraightforward\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just explain it directly" },
  { id: "ai.seamlessly", severity: "yellow", expression: /\bseamlessly\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe how it actually works" },
  { id: "ai.transformative", severity: "yellow", expression: /\btransformative\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what specifically changed" },
  { id: "ai.meaningful", severity: "yellow", expression: /\bmeaningful\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "be specific about what makes it meaningful" },
  { id: "ai.profound", severity: "yellow", expression: /\bprofound\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe the actual depth/impact" },
  { id: "ai.intricate", severity: "yellow", expression: /\bintricate\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "say what specifically is complex" },
  { id: "ai.cornerstone", severity: "red", expression: /\bcornerstone\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific foundation" },
  { id: "ai.navigate", severity: "yellow", expression: /\bnavigate\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe the specific action" },
  { id: "ai.endeavor", severity: "yellow", expression: /\bendeavor\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: effort, project, attempt" },
  { id: "ai.encapsulate", severity: "yellow", expression: /\bencapsulate[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: capture, contain, describe" },
  { id: "ai.facilitate", severity: "yellow", expression: /\bfacilitate[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: help, enable, support" },
  { id: "ai.bolster", severity: "yellow", expression: /\bbolster[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: strengthen, support, boost" },
  { id: "ai.streamline", severity: "yellow", expression: /\bstreamline[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what specifically was simplified" },
  { id: "ai.differentiate", severity: "yellow", expression: /\bdifferentiate[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what specifically is different" },
  { id: "ai.myriad", severity: "yellow", expression: /\bmyriad\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific number or items" },
  { id: "ai.elevate", severity: "yellow", expression: /\belevate[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what specifically improved" },
  { id: "ai.revolutionize", severity: "red", expression: /\brevolutionize[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe the specific change" },
  { id: "ai.supercharge", severity: "red", expression: /\bsupercharge[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe what it actually does" },
  { id: "ai.ensure", severity: "yellow", expression: /\bensure\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: make sure, confirm, verify" },
  { id: "ai.crucial", severity: "yellow", expression: /\bcrucial\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "explain why it matters specifically" },
  { id: "ai.vital", severity: "yellow", expression: /\bvital\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "describe the specific importance" },
  { id: "ai.cultivate", severity: "yellow", expression: /\bcultivate[sd]?\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "use: build, grow, develop" },
  { id: "ai.plethora", severity: "yellow", expression: /\bplethora\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "name the specific quantity or items" },
  { id: "ai.embark", severity: "red", expression: /\bembark\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just start. no embarking needed." },
  { id: "formula.firstly", severity: "yellow", expression: /\bfirstly\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'just start \u2014 "firstly" is filler' },
  { id: "formula.secondly", severity: "yellow", expression: /\bsecondly\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'just continue \u2014 "secondly" is filler' },
  { id: "formula.lastly", severity: "yellow", expression: /\blastly\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'just end \u2014 "lastly" is filler' },
  { id: "formula.moreover", severity: "yellow", expression: /\bmoreover\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just add the point" },
  { id: "formula.furthermore", severity: "yellow", expression: /\bfurthermore\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just add the point" },
  { id: "formula.in-conclusion", severity: "red", expression: /\bin conclusion\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just end. readers know it's the end." },
  { id: "formula.in-summary", severity: "red", expression: /\bin summary\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just summarize. the label is redundant." },
  { id: "formula.it-is-important", severity: "yellow", expression: /\bit is important to note\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just note it. skip the preamble." },
  { id: "formula.at-the-end", severity: "yellow", expression: /\bat the end of the day\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "cut this \u2014 it means nothing" },
  { id: "formula.needless-to-say", severity: "yellow", expression: /\bneedless to say\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "if it's needless, don't say it" },
  { id: "formula.it-goes-without", severity: "yellow", expression: /\bit goes without saying\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "then don't say it" },
  { id: "formula.in-today", severity: "red", expression: /\bin today'?s\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "start with your actual point instead" },
  { id: "formula.lets-dive", severity: "red", expression: /\blet'?s (?:dive|jump|dig|delve)\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just start. no diving needed." },
  { id: "formula.without-further", severity: "red", expression: /\bwithout further ado\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "cut this \u2014 just get to it" },
  { id: "formula.its-worth-noting", severity: "yellow", expression: /\bit'?s worth noting\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just note it directly" },
  { id: "formula.moving-forward", severity: "yellow", expression: /\bmoving forward\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just say what happens next" },
  { id: "formula.to-put-in-perspective", severity: "yellow", expression: /\bto put this in perspective\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just give the perspective directly" },
  { id: "formula.what-makes-interesting", severity: "yellow", expression: /\bwhat makes this particularly interesting\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just say the interesting thing" },
  { id: "formula.implications", severity: "yellow", expression: /\bthe implications here are\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "state the implications directly" },
  { id: "formula.in-other-words", severity: "red", expression: /\bin other words\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "say it once, well" },
  { id: "formula.here-the-thing", severity: "yellow", expression: /\bhere'?s the thing\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just say the thing" },
  { id: "formula.lets-be-clear", severity: "yellow", expression: /\blet'?s be clear\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just be clear. the announcement is filler." },
  { id: "formula.the-bottom-line", severity: "yellow", expression: /\bthe bottom line\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just state the conclusion" },
  { id: "formula.picture-this", severity: "yellow", expression: /\bpicture this\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just describe the scene" },
  { id: "formula.think-of-it", severity: "yellow", expression: /\bthink of it this way\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just explain it directly" },
  { id: "formula.when-it-comes-to", severity: "yellow", expression: /\bwhen it comes to\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just address the topic directly" },
  { id: "formula.the-reality-is", severity: "yellow", expression: /\bthe reality is\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "just state the reality" },
  { id: "hedge.some-might", severity: "yellow", expression: /\bsome might say\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "commit to the claim or drop it" },
  { id: "hedge.arguably", severity: "yellow", expression: /\barguably\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "commit. say it or don't." },
  { id: "hedge.worth-noting", severity: "yellow", expression: /\bit'?s worth noting\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "just note it directly" },
  { id: "hedge.to-some-extent", severity: "yellow", expression: /\bto some extent\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "be specific about the extent" },
  { id: "hedge.perhaps", severity: "yellow", expression: /\bperhaps\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "commit or cut" },
  { id: "hedge.maybe", severity: "yellow", expression: /\bmaybe\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "commit or cut" },
  { id: "hedge.possibly", severity: "yellow", expression: /\bpossibly\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "commit or cut" },
  { id: "hedge.it-seems", severity: "yellow", expression: /\bit seems\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "state it directly" },
  { id: "hedge.i-think", severity: "yellow", expression: /\bi think\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: 'just say it. the "i think" is implied.' },
  { id: "hedge.in-my-opinion", severity: "yellow", expression: /\bin my opinion\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "just state it. it's your article." },
  { id: "struct.antithesis", severity: "yellow", expression: /\bnot (?:just|only) .{3,50}, but .{3,50}/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "this antithesis pattern is an AI tell \u2014 restructure" },
  { id: "struct.not-just-but-also", severity: "yellow", expression: /\bnot\s+just\b.{3,80}\bbut\s+(?:also\s+)?/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "say what it IS, not what it isn't" },
  { id: "struct.more-than-just", severity: "yellow", expression: /\bmore\s+than\s+just\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "say what it IS, not what it isn't" },
  { id: "struct.in-order-to", severity: "yellow", expression: /\bin order to\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: 'just use "to"' },
  { id: "struct.due-to-the-fact", severity: "yellow", expression: /\bdue to the fact that\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: 'use "because"' },
  { id: "struct.for-the-purpose", severity: "yellow", expression: /\bfor the purpose of\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: 'use "to"' },
  { id: "struct.which-is-another", severity: "red", expression: /\bwhich is another way of saying\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "just say the thing directly" },
  { id: "struct.in-other-words", severity: "red", expression: /\bin other words\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "just say it once, well" },
  { id: "struct.rhetorical-truth", severity: "yellow", expression: /\b(?:the\s+)?(?:uncomfortable|hard|harsh|brutal|ugly|unsexy|real|honest)\s+(?:truth|reality)\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "state the fact directly, skip the framing" },
  { id: "struct.truth-is", severity: "yellow", expression: /\bthe\s+truth\s+is\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "just say the truth. the framing is filler." },
  { id: "struct.lesson-setup", severity: "yellow", expression: /\b(?:here'?s\s+)?what\s+.{3,80}\s+(?:taught|teaches)\s+(?:me|us|you|everyone)\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "just share the lesson" },
  { id: "struct.negation-cascade", severity: "yellow", expression: /\b(?:no|not)\s+\w[^.!?\n]{0,80}[.!?][ \t]*\n?[ \t]*(?:no|not)\s+\w[^.!?\n]{0,80}[.!?][ \t]*\n?[ \t]*(?:no|not)\s+\w/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "three negations in a row reads like AI performance", scope: "line" },
  { id: "struct.inline-triplet", severity: "yellow", expression: /\bit'?s\s+\w[^,.!?;\n]{0,30},\s*it'?s\s+\w[^,.!?;\n]{0,30}[,.]?\s*(?:and\s+)?it'?s\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: `the "it's X, it's Y, it's Z" pattern is an AI tell` },
  { id: "struct.moment-becomes", severity: "red", expression: /\b(?:the\s+)?moment\b.{3,80}\bbecomes?\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: '"the moment X becomes Y" is polished founder cadence \u2014 restructure' },
  { id: "struct.same-better", severity: "red", expression: /\bsame\s+[^.!?\n]{1,35}[.!?]\s*(?:better|nicer|cleaner|calmer|safer)\s+[^.!?\n]{1,35}[.!?]?/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: '"same X. better Y." is screenshot-ready founder cadence', scope: "line" },
  { id: "struct.this-is-why", severity: "yellow", expression: /\bthis\s+is\s+(?:also\s+)?(?:why|how|where|what\b)/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "signpost claims are AI tells \u2014 just make the point" },
  { id: "struct.heres-where", severity: "yellow", expression: /\b(?:here'?s|here\s+is)\s+(?:where|why|what|the\s+part|the\s+(?:harder|real|actual|main|bigger)\s+problem)\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "just make the point without the signpost" },
  { id: "struct.generic-buyer", severity: "red", expression: /\bpeople\s+don'?t\s+just\s+buy\b|\bpeople\s+buy\s+the\s+feeling\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "generic buyer psychology is AI filler" },
  { id: "struct.this-isnt-x-this-is-y", severity: "red", expression: /\bthis isn'?t .{2,40}\.?\s*(?:this is|it'?s) .{2,40}/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "FATAL: delete the negation, just state the positive claim", scope: "line" },
  { id: "struct.not-x-y", severity: "red", expression: /\bnot .{2,30}\.?\s*.{2,30}\b/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: 'the "Not X. Y." pattern is an AI tell \u2014 just state Y', scope: "line" },
  { id: "struct.forget-x", severity: "red", expression: /\bforget .{2,40}\.?\s*(?:this is|it'?s|you need)/i, reason: "A formulaic structure can make the sentence feel manufactured.", suggestion: "don't negate \u2014 just state what you mean", scope: "line" },
  { id: "punct.em-dash", severity: "yellow", expression: /—/, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "em dashes are an AI tell \u2014 use a period, comma, or parentheses" },
  { id: "bait.let-that-sink", severity: "red", expression: /\blet that sink in\b/i, reason: "The phrase asks for attention instead of earning it.", suggestion: "cut the sink. make your point and move on." },
  { id: "bait.read-that-again", severity: "red", expression: /\bread that again\b/i, reason: "The phrase asks for attention instead of earning it.", suggestion: "if it needs repeating, repeat it yourself" },
  { id: "bait.full-stop", severity: "red", expression: /\bfull stop\b/i, reason: "The phrase asks for attention instead of earning it.", suggestion: "the period already does this job" },
  { id: "bait.this-changes-everything", severity: "red", expression: /\bthis changes everything\b/i, reason: "The phrase asks for attention instead of earning it.", suggestion: "prove it with specifics" },
  { id: "bait.paying-attention", severity: "red", expression: /\bare you paying attention\b/i, reason: "The phrase asks for attention instead of earning it.", suggestion: "don't patronize the reader" },
  { id: "bait.not-ready", severity: "red", expression: /\byou'?re not ready for this\b/i, reason: "The phrase asks for attention instead of earning it.", suggestion: "just deliver the content" },
  { id: "cringe.future-proof", severity: "red", expression: /\bfuture[\s-]proof\b/i, reason: "The phrase makes a broad promotional claim without evidence.", suggestion: "explain what specifically makes it durable" },
  { id: "cringe.10x", severity: "red", expression: /\b10x\b/i, reason: "The phrase makes a broad promotional claim without evidence.", suggestion: "use the actual numbers" },
  { id: "cringe.ai-revolution", severity: "red", expression: /\bthe ai revolution\b/i, reason: "The phrase makes a broad promotional claim without evidence.", suggestion: "describe the specific change" },
  { id: "cringe.age-of-ai", severity: "red", expression: /\bin the age of ai\b/i, reason: "The phrase makes a broad promotional claim without evidence.", suggestion: "just talk about what's happening now" },
  { id: "cringe.happy-to-help", severity: "red", expression: /\bi'?d be happy to help\b/i, reason: "The phrase makes a broad promotional claim without evidence.", suggestion: "just help. don't announce it." },
  { id: "cringe.of-course", severity: "yellow", expression: /^of course!?\s/i, reason: "The phrase makes a broad promotional claim without evidence.", suggestion: "just answer. skip the enthusiasm.", scope: "line" },
  { id: "cringe.great-question", severity: "red", expression: /\bgreat question!?\b/i, reason: "The phrase makes a broad promotional claim without evidence.", suggestion: "just answer the question" },
  { id: "insider.nobody-talking", severity: "red", expression: /\bhere'?s the part nobody'?s? talking about\b/i, reason: "The framing claims privileged insight instead of stating the point.", suggestion: "just say the thing. the framing is noise." },
  { id: "insider.nobody-tells", severity: "red", expression: /\bwhat nobody tells you\b/i, reason: "The framing claims privileged insight instead of stating the point.", suggestion: "just tell them." },
  { id: "insider.most-people", severity: "yellow", expression: /\bmost people don'?t realize\b/i, reason: "The framing claims privileged insight instead of stating the point.", suggestion: "just explain it. skip the setup." },
  { id: "insider.nobody-realizes", severity: "red", expression: /\bnobody (?:realizes|talks about|mentions)\b/i, reason: "The framing claims privileged insight instead of stating the point.", suggestion: "if nobody talks about it, just talk about it" },
  { id: "ogilvy.bandwidth", severity: "yellow", expression: /\bbandwidth\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'Ogilvy: say "time" or "capacity"' },
  { id: "ogilvy.circle-back", severity: "red", expression: /\bcircle back\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'Ogilvy: say "follow up" or "talk later"' },
  { id: "ogilvy.low-hanging", severity: "red", expression: /\blow-hanging fruit\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "Ogilvy: name the specific easy win" },
  { id: "ogilvy.move-the-needle", severity: "red", expression: /\bmove the needle\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: "Ogilvy: describe the actual impact" },
  { id: "ogilvy.touch-base", severity: "red", expression: /\btouch base\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'Ogilvy: say "talk" or "meet"' },
  { id: "ogilvy.take-it-offline", severity: "red", expression: /\btake it offline\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'Ogilvy: say "discuss later"' },
  { id: "ogilvy.deep-dive", severity: "yellow", expression: /\bdeep dive\b/i, reason: "A stock phrase can flatten the writer's meaning.", suggestion: 'Ogilvy: say "look closely at" or "examine"' },
  { id: "ogilvy.preamble-i-want-to", severity: "yellow", expression: /^\s*i want to (?:share|talk about|discuss|mention)\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "Ogilvy: just say it. skip the preamble.", scope: "line" },
  { id: "ogilvy.preamble-just-wanted", severity: "yellow", expression: /^\s*(?:i just wanted|i wanted to)\b/i, reason: "A hedge or preamble weakens the direct claim.", suggestion: "Ogilvy: just say it.", scope: "line" },
  { id: "ai.question-hook", severity: "yellow", expression: /^(?:have you|do you|what if|why do|how do)\b/i, reason: "A question opener delays the concrete observation.", suggestion: "Open from an observation." },
  { id: "ai.abstract-cluster", severity: "yellow", expression: /\b(?:alignment|authenticity|clarity|strategy|value)\b.*\b(?:alignment|authenticity|clarity|strategy|value)\b/i, reason: "Abstract nouns pile up without a mechanism.", suggestion: "Use concrete nouns and actions." },
];
